apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-openshift
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cseoc-app
  template:
    metadata:
      labels:
        app: csekub-app
    spec:
      containers:
      - name: springboot-openshift-container
        image: ydprjy/cseoc:latest
        ports:
        - containerPort: 8085